-- Common starting point for loading plugins + configurations
require("plugins")
require("config/mason")
require("config/clangd")
require("config/cmp")
require("config/lsp")
require("config/zenmode")
require("config/gruvbox")
require("config/ts")
require("config/mkdnflow")
require("config/telekasten")
require("config/other")
require("config/kommentary")
require("config/project")
require("config/asynctasks")
require("config/notify")
require("config/dap")

require("options")
require("mappings")

